[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "dag_builder"
version = "0.1.0"
dependencies = [
    "pydantic>=2.0.0",
    "dlt[sqlalchemy]",
    "pyyaml",
    "requests",
    "duckdb",
    "pandas",
    "dbt-core",
    "dbt-duckdb"
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-cov",
    "pytest-mock",
    "pylint"
]

[tool.setuptools.packages.find]
include = ["dag_builder*"]
exclude = ["logs", "build", "examples", "example", "dag_builder.egg-info"]
