[pytest]
# Run coverage when running tests; report missing lines in the terminal.
addopts = --cov=dag_builder --cov-report=term-missing

filterwarnings =
    ignore:Airflow currently can be run on POSIX-compliant Operating Systems:RuntimeWarning
    ignore:The `airflow.hooks.base.BaseHook` attribute is deprecated:DeprecationWarning
